//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KN_ProyectoClase.BaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsuariosOferta
    {
        public long Id { get; set; }
        public long IdUsuario { get; set; }
        public long IdOferta { get; set; }
        public System.DateTime Fecha { get; set; }
        public int Estado { get; set; }
    
        public virtual Oferta Oferta { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
